// sync-core.mjs — copy the self-contained half of frontend/common/ into the
// iOS app as ES modules.
//
// The web frontend is classic scripts in one global scope; React Native needs
// modules. Rather than change the web (its files stay byte-for-byte as they
// are), we copy the files that are genuinely self-contained and append an
// `export { … }` footer generated from their top-level declarations.
//
// The point is dates.js: its grammar already has to stay in lockstep with
// backend/date_utils.py by hand, and a third hand-maintained copy in the app
// would be a standing bug. Copying keeps one JS source of truth.
//
//   node scripts/sync-core.mjs           regenerate app/src/core/
//   node scripts/sync-core.mjs --check   exit 1 if stale (for CI)
//
// Adding a file here is a claim that it is self-contained. Run
// scripts/analyze-core.mjs to check that claim before you make it.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as acorn from 'acorn';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const COMMON_DIR = join(ROOT, '..', 'frontend', 'common');
const OUT_DIR = join(ROOT, 'src', 'core');

// Each entry: the file, and any top-level name that must NOT be exported
// because its body reaches for something only a browser has. Importing such a
// file is safe (the free variables are inside the function); calling it is not,
// so we refuse to export it at all and the app cannot call it by accident.
const SHARED = [
  { file: 'constants.js', omit: [] },
  { file: 'dates.js', omit: [] },
  { file: 'collapse.js', omit: [] },
  // applyLangToStaticUI writes into index.html's DOM and reaches for addPanel /
  // renderCustomLoadBtn, neither of which exists in the app. Everything else in
  // the file — TRANSLATIONS, t, lang, translateLabel — is pure.
  { file: 'i18n.js', omit: ['applyLangToStaticUI'] },
];

function topLevelNames(src, file) {
  const ast = acorn.parse(src, { ecmaVersion: 2022, sourceType: 'script' });
  const names = [];
  for (const node of ast.body) {
    if (node.type === 'VariableDeclaration') {
      for (const d of node.declarations) {
        if (d.id.type !== 'Identifier') {
          throw new Error(`${file}: destructuring at top level is not supported`);
        }
        names.push(d.id.name);
      }
    } else if (node.type === 'FunctionDeclaration' || node.type === 'ClassDeclaration') {
      names.push(node.id.name);
    }
  }
  return names;
}

function generate({ file, omit }) {
  const srcPath = join(COMMON_DIR, file);
  const src = readFileSync(srcPath, 'utf8');
  const names = topLevelNames(src, file);

  for (const name of omit) {
    if (!names.includes(name)) {
      throw new Error(`${file}: cannot omit '${name}' — it is not declared at top level`);
    }
  }
  const exported = names.filter(n => !omit.includes(n));

  const banner = [
    `// GENERATED by app/scripts/sync-core.mjs from frontend/common/${file}`,
    `// Do not edit. Edit the source file and run \`npm run sync-core\`.`,
    omit.length
      ? `// Deliberately not exported (browser-only): ${omit.join(', ')}`
      : null,
    '',
  ].filter(v => v !== null).join('\n');

  const footer = `\nexport {\n${exported.map(n => `  ${n},`).join('\n')}\n};\n`;

  return { name: file, content: banner + src + footer };
}

// Node needs to be told these .js files are ES modules. A nested package.json
// scopes that to src/core/ only, so the Expo app's own package.json stays
// CommonJS-by-default the way the RN toolchain expects. Metro ignores this.
const CORE_PKG = JSON.stringify({ type: 'module' }, null, 2) + '\n';

const outputs = [
  ...SHARED.map(generate),
  { name: 'package.json', content: CORE_PKG },
];
const check = process.argv.includes('--check');

if (!check) mkdirSync(OUT_DIR, { recursive: true });

let stale = 0;
for (const { name, content } of outputs) {
  const dest = join(OUT_DIR, name);
  const current = existsSync(dest) ? readFileSync(dest, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`stale: src/core/${name}`);
    stale++;
  } else {
    writeFileSync(dest, content);
    console.log(`wrote src/core/${name}`);
  }
}

if (check) {
  if (stale) {
    console.error(`\n${stale} file(s) out of date. Run \`npm run sync-core\`.`);
    process.exit(1);
  }
  console.log(`src/core/ is up to date (${SHARED.length} shared files).`);
} else {
  console.log(`\n${SHARED.length} file(s) synced from frontend/common/.`);
}
